# Generated by Django 5.2.6 on 2025-09-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custemuser',
            name='is_admin_user',
        ),
        migrations.RemoveField(
            model_name='custemuser',
            name='is_member_user',
        ),
        migrations.RemoveField(
            model_name='custemuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='custemuser',
            name='is_family_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custemuser',
            name='is_family_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custemuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
