# Generated by Django 5.2.6 on 2025-09-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_album_albumphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='shared_family',
            new_name='share_family',
        ),
    ]
