# Generated by Django 5.2.6 on 2025-11-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_custemuser_bio_custemuser_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custemuser',
            name='bio',
        ),
        migrations.AddField(
            model_name='custemuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
